### ISSUE TITLE
hexo g失败

### ISSUE THREAD

**Issue by Asthestarsfalll** [callmesoul/hexo-theme-soul#4]
所有index.html都为空

**Comment by Asthestarsfalll** [comment]
![image](https://user-images.githubusercontent.com/72954905/121807199-bf789700-cc85-11eb-900c-42800c9e2908.png)

**Comment by callmesoul** [comment]
hexo 版本对么？

**Comment by Asthestarsfalll** [comment]
> hexo 版本对么？

4.2.0

**Comment by callmesoul** [comment]
> > hexo 版本对么？
> 
> 4.2.0

你试下升到 5.4.0

**Comment by Asthestarsfalll** [comment]
> > > hexo 版本对么？
> > 
> > 
> > 4.2.0
> 
> 你试下升到 5.4.0

我用的linux系统，已经是最新了

**Comment by callmesoul** [comment]
@Asthestarsfalll 不好意思哦，看了跑了项目，发现一些问题，最近比较忙，我找时间修修
